name: Publish Docker Image
on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t aminetakha/multi-client ./client
      - uses: actions/checkout@v2
      - run: docker build -t aminetakha/multi-nginx ./nginx
      - uses: actions/checkout@v2
      - run: docker build -t aminetakha/multi-worker ./worker
      - uses: actions/checkout@v2
      - run: docker build -t aminetakha/multi-server ./server
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push aminetakha/multi-client
      - run: docker push aminetakha/multi-nginx
      - run: docker push aminetakha/multi-worker
      - run: docker push aminetakha/multi-server

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Multidocker-env
          version_label: "Sample Application"
          region: us-east-2
