name: Test and push
on:
  push:
    branches: [main]

jobs:
  test_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t aminetakha/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run aminetakha/react-test yarn run test -- --watchAll=false
      - run: docker build -t aminetakha/multi-react ./client
      - run: docker build -t aminetakha/multi-nginx ./nginx
      - run: docker build -t aminetakha/multi-server ./server
      - run: docker build -t aminetakha/multi-worker ./worker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push aminetakha/multi-react
      - run: docker push aminetakha/multi-nginx
      - run: docker push aminetakha/multi-server
      - run: docker push aminetakha/multi-worker
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.ENV_NAME }}
          existing_bucket_name: ${{ secrets.BUCKET_NAME }}
          region: ${{ secrets.REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
